export default {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  INPUT_CHANGE: "INPUT_CHANGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",

  FETCH_CURRENT_USER: "FETCH_CURRENT_USER",
  FETCH_ALL_USERS: "FETCH_ALL_USERS",
  FETCH_SECTIONS: "FETCH_SECTIONS",
  FETCH_DIVISION: "FETCH_DIVISION",
  FETCH_DOC_TYPES: "FETCH_DOC_TYPES",

  EDIT: "EDIT",
  UPDATE: "UPDATE",
  CLOSE_MODAL: "CLOSE_MODAL",
  INPUT_CHANGE_USER: "INPUT_CHANGE_USER",

  SEARCH: "SEARCH",
  SORT: "SORT",

  USER_REG: "USER_REG",
};
